const commando = require('discord.js-commando');
const Discord = module.require('discord.js');
const mongodb = require('mongodb');
const MongoClient = mongodb.MongoClient;
var url = 'mongodb://atlantius:idioticons@ds235169.mlab.com:35169/devbot'

class XP extends commando.Command {
  constructor(client) {
    super(client, {
      name: 'xp',
      group: 'game',
      memberName: 'xp',
      description: 'Check your experience and level'
    });
  }

  async run(message, args) {
    // console.log(message)
    let target = message.mentions.users.first() || message.author;


    MongoClient.connect(url, function (err, client) {
      if (err) throw err;
      var db = client.db('devbot');
      db.collection('test').findOne({ id: `${message.author.id}` }, function (findErr, result) {
        // console.log(target.id)
        if (findErr) throw findErr;
        let xp = db.collection('test').findOne({ id: message.author.id }).then(function (numItems) {
          //  console.log(numItems)
          let embed = new Discord.RichEmbed()
            .setTitle(`${target.username} statistics`)
            .setDescription(`Level 0 is for loosers`)
            .addField('Experience', numItems.xp.toString(), true)
            .addField('Level', numItems.level.toString(), true)
            .setFooter(`Generated by DevBot`)

          message.channel.send({ embed });
        })
        client.close();
      });
    });




  }
}

module.exports = XP;
